name: "test"

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
